//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMusicServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lyric
    {
        public long Id { get; set; }
        public string Lyric1 { get; set; }
        public long SongId { get; set; }
        public int UserId { get; set; }
        public bool Verified { get; set; }
    
        public virtual Song Song { get; set; }
        public virtual User User { get; set; }
    }
}
