//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMusicServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaylistComment
    {
        public long Id { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
        public int UserId { get; set; }
        public int PlaylistId { get; set; }
    
        public virtual Playlist Playlist { get; set; }
        public virtual User User { get; set; }
    }
}
