//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineMusicServices.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SongView
    {
        public long Id { get; set; }
        public long SongId { get; set; }
        public string Ip { get; set; }
        public System.DateTime Timestamp { get; set; }
        public long Views { get; set; }
    
        public virtual Song Song { get; set; }
    }
}
